builders:
  ast_builder:
    import: "package:gql_build/gql_build.dart"
    builder_factories: ["astBuilder"]
    build_extensions: { ".graphql": [".ast.gql.dart"] }
    auto_apply: none
    build_to: source
  op_builder:
    import: "package:gql_build/gql_build.dart"
    builder_factories: ["opBuilder"]
    build_extensions: { ".graphql": [".op.gql.dart"] }
    auto_apply: none
    build_to: source
  data_builder:
    import: "package:gql_build/gql_build.dart"
    builder_factories: ["dataBuilder"]
    build_extensions: { ".graphql": [".data.gql.dart"] }
    auto_apply: none
    build_to: source
  req_builder:
    import: "package:gql_build/gql_build.dart"
    builder_factories: ["reqBuilder"]
    build_extensions: { ".graphql": [".req.gql.dart"] }
    auto_apply: none
    build_to: source
  var_builder:
    import: "package:gql_build/gql_build.dart"
    builder_factories: ["varBuilder"]
    build_extensions: { ".graphql": [".var.gql.dart"] }
    auto_apply: none
    build_to: source
  schema_builder:
    import: "package:gql_build/gql_build.dart"
    builder_factories: ["schemaBuilder"]
    build_extensions: { ".graphql": [".schema.gql.dart"] }
    auto_apply: none
    build_to: source
