name: gql_example_cli
environment: 
  sdk: '>=2.7.0 <3.0.0'
dependencies: 
  args: any
  gql: ^0.12.3
  gql_link: ^0.3.0
  gql_exec: ^0.2.4
  gql_http_link: ^0.2.9
dev_dependencies: 
  build_runner: ^1.0.0
  gql_pedantic: ^1.0.2
  gql_build: ^0.0.11
